# Generated by Django 3.0.6 on 2020-05-10 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('ballot_id', models.AutoField(primary_key=True, serialize=False)),
                ('ballot_name', models.CharField(max_length=500, unique=True)),
                ('ballot_address', models.CharField(max_length=500)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('ballot_end_date', models.DateTimeField(null=True)),
                ('ballot_interface', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BallotRegister',
            fields=[
                ('ballot_register_id', models.AutoField(primary_key=True, serialize=False)),
                ('voted', models.BooleanField(default=False)),
                ('registered', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Ballot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AddressBallotRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_string', models.TextField(unique=True)),
                ('address', models.TextField()),
                ('private_key', models.TextField()),
                ('tx_hash', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Ballot')),
            ],
        ),
        migrations.AddConstraint(
            model_name='ballotregister',
            constraint=models.UniqueConstraint(fields=('user_id', 'ballot_id'), name='uniqueBallotRegister'),
        ),
    ]
